### ISSUE TITLE
Reduce cross-file test-suite flakiness under full parallel make check runs

### ISSUE THREAD

**Issue by cfornesa** [cfornesa/ai-dev-tools-zoomcamp-1#302]
## Problem

Observed repeatedly across multiple agent sessions working in this repo (not isolated to one run): isolated ~5-second timeout failures on unrelated frontend test files (e.g. `EditorWorkspace.a11y.test.tsx`, `EditorWorkspace.multiTransform.test.tsx`, `EditorWorkspace.selectionHud.test.tsx`) during a full parallel `make check`/`npm test` run. Each of these files passes cleanly and quickly when run in isolation (`npx vitest run <file>`). Never reproduced as a deterministic failure (no fixed file/test always fails), which points at test-infrastructure/parallel-worker resource contention rather than a product defect in any of the affected tests.

## Scope

- Investigate whether Vitest's pool/worker configuration (`frontend/vitest.config.ts`) needs tuning for this repo's current test-file count (~180 files) and typical CI/local hardware -- e.g. `pool: 'threads'` options, `maxWorkers`/`minWorkers`, a higher default `testTimeout`.
- Alternatively/additionally, check whether any commonly-affected test files share a timing assumption (fake timers, `requestAnimationFrame`, real timeouts) that only breaks under CPU/memory pressure from many workers running concurrently.
- Not in scope: rewriting the affected tests' actual assertions -- they are correct and pass in isolation.

## Acceptance criteria

- [ ] A full `make check`/`npm test` run completes without an unrelated file's isolated timeout failure, across several repeated runs.
- [ ] If a config change is made (e.g. to `vitest.config.ts`), document the reasoning and the tuning that fixed it.
- [ ] `make check` passes.

## Discovery

Flagged in multiple QA comments and `docs/tasks.md` notes across sessions as a probable test-infrastructure issue, but never filed as its own dedicated issue until now (distilled via `task-distillation` during this session's batch backlog processing).

## Dependencies

None.

**Comment by cfornesa** [comment]
## QA: PASS

### Criterion matrix

| Criterion | Result |
| --- | --- |
| A full `make check`/`npm test` run completes without an unrelated file's isolated timeout failure, across several repeated runs | PASS — 4 consecutive full runs (3x `npm test`, 1x full `make check`), all green, 2290/2290 frontend tests passing every time. |
| If a config change is made, document the reasoning and the tuning that fixed it | PASS — see below and the code comment in `frontend/vite.config.ts`. |
| `make check` passes | PASS — 876 backend / 2290 frontend. |

### Root cause and fix

`frontend/vite.config.ts`'s `test` block had no `testTimeout`/`hookTimeout` override, so Vitest's *default* 5000ms applied to every test. With ~180 test files split across this machine's worker pool, occasional CPU contention (this session also had Django + Vite dev servers running concurrently, plus the browser automation driving them) was enough to push some tests' real async work (userEvent interactions, component mount/unmount, timers) past that 5s ceiling — even though the exact same test finishes in well under a second in isolation with no contention. This matches the reported symptom exactly: never a fixed file, never reproducible deterministically, always a fast pass alone.

Tripled both `testTimeout` and `hookTimeout` to 15000ms — real headroom under contention, while still a hard ceiling that would catch an actually-hung test. No test file's own code needed changing, matching the issue's own scope note that the affected tests are correct.

### Commands

```
cd frontend && npm test   # x3 consecutive runs, all green
cd .. && make check       # full backend + frontend gate, green
```

### Verification

Ran the full frontend suite 3 times in a row plus one full `make check` — 181/181 test files, 2290/2290 tests passed every time, no isolated timeout failures. This can't prove the flakiness is eliminated with certainty (it was never deterministic to begin with), but 4 clean consecutive runs after the only plausible root cause was addressed is strong evidence, and the fix itself (removing an artificially tight timeout under known contention) is sound regardless.

Commit: 68ba99d

**Comment by cfornesa** [comment]
Closing — root cause identified and fixed, verified via repeated clean runs per the QA comment above.
